[package]
name = "jams-desktop"
version = "0.1.0"
description = "JAMS Desktop"
authors = ["cobite", "loziniak", "Nick Virag"]
license = "UNLICENSED"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jams_lib"
path = "src/lib.rs" 
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
warp = "*"
tauri = { version = "2.0.1", features = [] }
tauri-plugin-shell = "2.0.1"
tauri-plugin-store = "2.0.1"
tauri-plugin-fs = "2.0.1"
tauri-plugin-dialog = "2.0.1"
tauri-plugin-http = "2.0.1"
lazy_static = "1.4.0"
 # path to local copy of https://github.com/JAMSplayer/safe
safe = { path = "../../../maidsafe/safe" }

