export type Song = {
    address?: string;
    index?: number;
    uuid?: string;
    title: string;
    artist: string;
    album: string;
    file?: string;
    art?: string;
    dateCreated?: Date;
    dateUpdated?: Date;
    genre: string;
    year: string;
    tags: string[];
    broadcasts?: string[];
    playlists?: string[];
    isPublic?: boolean;
    favorite?: boolean;
    originalUploader?: boolean;
    id?: number;
    localIndex?: number;
    location: string;
};
